/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The type of Risk Cloud application
 */
export enum ApplicationPropertyApiOutType {
    AccessManagement = "ACCESS_MANAGEMENT",
    AmlKyc = "AML_KYC",
    AssetManagement = "ASSET_MANAGEMENT",
    AuditManagement = "AUDIT_MANAGEMENT",
    BusinessContinuityPlanning = "BUSINESS_CONTINUITY_PLANNING",
    ChangeManagement = "CHANGE_MANAGEMENT",
    ComplaintManagement = "COMPLAINT_MANAGEMENT",
    ComplianceManagement = "COMPLIANCE_MANAGEMENT",
    ContractManagement = "CONTRACT_MANAGEMENT",
    ControlsCompliance = "CONTROLS_COMPLIANCE",
    ControlsManagement = "CONTROLS_MANAGEMENT",
    CrisisManagement = "CRISIS_MANAGEMENT",
    Custom = "CUSTOM",
    CustomGrcUseCase = "CUSTOM_GRC_USE_CASE",
    CyberRiskManagement = "CYBER_RISK_MANAGEMENT",
    DataPrivacyManagement = "DATA_PRIVACY_MANAGEMENT",
    EmployeeCompliance = "EMPLOYEE_COMPLIANCE",
    EnterpriseRiskManagement = "ENTERPRISE_RISK_MANAGEMENT",
    Esg = "ESG",
    IncidentManagement = "INCIDENT_MANAGEMENT",
    InternalAuditManagement = "INTERNAL_AUDIT_MANAGEMENT",
    ItRiskManagement = "IT_RISK_MANAGEMENT",
    None = "NONE",
    OperationalResiliency = "OPERATIONAL_RESILIENCY",
    Other = "OTHER",
    PolicyAndProcedureManagement = "POLICY_AND_PROCEDURE_MANAGEMENT",
    PolicyManagement = "POLICY_MANAGEMENT",
    PrivacyManagement = "PRIVACY_MANAGEMENT",
    Quantify = "QUANTIFY",
    RegulatoryCompliance = "REGULATORY_COMPLIANCE",
    Repository = "REPOSITORY",
    RiskQuantification = "RISK_QUANTIFICATION",
    SoxTesting = "SOX_TESTING",
    StandardsRegulations = "STANDARDS_REGULATIONS",
    Survey = "SURVEY",
    ThirdPartyRiskManagement = "THIRD_PARTY_RISK_MANAGEMENT",
}

/**
 * The parent application of the record
 */
export class ApplicationPropertyApiOut extends SpeakeasyBase {
    /**
     * The unique ID of this Risk Cloud resource
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The name of the application
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Identifies the type of object this data represents
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object?: string;

    /**
     * The type of Risk Cloud application
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: ApplicationPropertyApiOutType;
}
