/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The icon type of the application (defaults to CUBES)
 */
export enum ApplicationApiCreateInIcon {
    Bookmark = "BOOKMARK",
    Bolt = "BOLT",
    Bullhorn = "BULLHORN",
    Certificate = "CERTIFICATE",
    CheckSquareO = "CHECK_SQUARE_O",
    Cloud = "CLOUD",
    Comments = "COMMENTS",
    Cubes = "CUBES",
    Dollar = "DOLLAR",
    ExclamationTriangle = "EXCLAMATION_TRIANGLE",
    TextO = "TEXT_O",
    Folder = "FOLDER",
    Gift = "GIFT",
    Globe = "GLOBE",
    Heartbeat = "HEARTBEAT",
    Leaf = "LEAF",
    Legal = "LEGAL",
    LifeRing = "LIFE_RING",
    Medkit = "MEDKIT",
    Money = "MONEY",
    Percent = "PERCENT",
    Rocket = "ROCKET",
    Signal = "SIGNAL",
    University = "UNIVERSITY",
    UserCircle = "USER_CIRCLE",
}

/**
 * The type of Risk Cloud application (defaults to NONE)
 */
export enum ApplicationApiCreateInType {
    AccessManagement = "ACCESS_MANAGEMENT",
    AmlKyc = "AML_KYC",
    AssetManagement = "ASSET_MANAGEMENT",
    AuditManagement = "AUDIT_MANAGEMENT",
    BusinessContinuityPlanning = "BUSINESS_CONTINUITY_PLANNING",
    ChangeManagement = "CHANGE_MANAGEMENT",
    ComplaintManagement = "COMPLAINT_MANAGEMENT",
    ComplianceManagement = "COMPLIANCE_MANAGEMENT",
    ContractManagement = "CONTRACT_MANAGEMENT",
    ControlsCompliance = "CONTROLS_COMPLIANCE",
    ControlsManagement = "CONTROLS_MANAGEMENT",
    CrisisManagement = "CRISIS_MANAGEMENT",
    Custom = "CUSTOM",
    CustomGrcUseCase = "CUSTOM_GRC_USE_CASE",
    CyberRiskManagement = "CYBER_RISK_MANAGEMENT",
    DataPrivacyManagement = "DATA_PRIVACY_MANAGEMENT",
    EmployeeCompliance = "EMPLOYEE_COMPLIANCE",
    EnterpriseRiskManagement = "ENTERPRISE_RISK_MANAGEMENT",
    Esg = "ESG",
    IncidentManagement = "INCIDENT_MANAGEMENT",
    InternalAuditManagement = "INTERNAL_AUDIT_MANAGEMENT",
    ItRiskManagement = "IT_RISK_MANAGEMENT",
    None = "NONE",
    OperationalResiliency = "OPERATIONAL_RESILIENCY",
    Other = "OTHER",
    PolicyAndProcedureManagement = "POLICY_AND_PROCEDURE_MANAGEMENT",
    PolicyManagement = "POLICY_MANAGEMENT",
    PrivacyManagement = "PRIVACY_MANAGEMENT",
    Quantify = "QUANTIFY",
    RegulatoryCompliance = "REGULATORY_COMPLIANCE",
    Repository = "REPOSITORY",
    RiskQuantification = "RISK_QUANTIFICATION",
    SoxTesting = "SOX_TESTING",
    StandardsRegulations = "STANDARDS_REGULATIONS",
    Survey = "SURVEY",
    ThirdPartyRiskManagement = "THIRD_PARTY_RISK_MANAGEMENT",
}

export class ApplicationApiCreateIn extends SpeakeasyBase {
    /**
     * The hex representation of the icon color of the application (defaults to #00a3de)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "color" })
    color?: string;

    /**
     * The icon type of the application (defaults to CUBES)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "icon" })
    icon?: ApplicationApiCreateInIcon;

    /**
     * The name of the application
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The type of Risk Cloud application (defaults to NONE)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: ApplicationApiCreateInType;
}
