/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ValuePropertyApiOut } from "./valuepropertyapiout";
import { Expose, Type } from "class-transformer";

/**
 * The type of the field
 */
export enum FieldRecordApiOutFieldType {
    Date = "DATE",
    User = "USER",
    ExternalUser = "EXTERNAL_USER",
    Text = "TEXT",
    TextArea = "TEXT_AREA",
    Number = "NUMBER",
    ESignature = "E_SIGNATURE",
    Checkbox = "CHECKBOX",
    MultiSelect = "MULTI_SELECT",
    Radio = "RADIO",
    Select = "SELECT",
    Attachment = "ATTACHMENT",
    Calculation = "CALCULATION",
    DateCalculation = "DATE_CALCULATION",
    Other = "OTHER",
}

/**
 * The type of the field value
 */
export enum FieldRecordApiOutValueType {
    Number = "NUMBER",
    Calculation = "CALCULATION",
    Attachment = "ATTACHMENT",
    Date = "DATE",
    Option = "OPTION",
    User = "USER",
    Text = "TEXT",
    Other = "OTHER",
}

/**
 * The fields and values of the record
 */
export class FieldRecordApiOut extends SpeakeasyBase {
    /**
     * Whether the field is global
     */
    @SpeakeasyMetadata()
    @Expose({ name: "global" })
    global?: boolean;

    /**
     * The unique ID of this Risk Cloud resource
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The label of the field as shown on the record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "label" })
    label?: string;

    /**
     * The name of the field
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Identifies the type of object this data represents
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object?: string;

    /**
     * The type of the field
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: FieldRecordApiOutFieldType;

    /**
     * The type of the field value
     */
    @SpeakeasyMetadata()
    @Expose({ name: "valueType" })
    valueType?: FieldRecordApiOutValueType;

    /**
     * The values of the record field
     */
    @SpeakeasyMetadata({ elemType: ValuePropertyApiOut })
    @Expose({ name: "values" })
    @Type(() => ValuePropertyApiOut)
    values?: ValuePropertyApiOut[];
}
