/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class LegacyApiTokenOut extends SpeakeasyBase {
    /**
     * An API access token to be used within the bearer authorization header of subsequent Risk Cloud API requests
     */
    @SpeakeasyMetadata()
    @Expose({ name: "access_token" })
    accessToken?: string;

    /**
     * The remaining time in seconds until the token expires
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expires_in" })
    expiresIn?: number;

    /**
     * The privilege scope of the token, expected to be "read write" for the Risk Cloud API
     */
    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope?: string;

    /**
     * The token type, expected to be "bearer" for the Risk Cloud API
     */
    @SpeakeasyMetadata()
    @Expose({ name: "token_type" })
    tokenType?: string;
}
