/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A collection of page URL links for navigation and iteration
 */
export class PageLinksOut extends SpeakeasyBase {
    /**
     * A URL path to the first page of requested data
     */
    @SpeakeasyMetadata()
    @Expose({ name: "first" })
    first?: string;

    /**
     * A URL link to the last page of requested data
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last" })
    last?: string;

    /**
     * A URL link to the next page of requested data or `null` if currently on last page
     */
    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    /**
     * A URL path to the next page of requested data or `null` if currently on first page
     */
    @SpeakeasyMetadata()
    @Expose({ name: "prev" })
    prev?: string;

    /**
     * A URL path to the current page of requested data
     */
    @SpeakeasyMetadata()
    @Expose({ name: "self" })
    self?: string;
}
