/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PageInfoOut } from "./pageinfoout";
import { PageLinksOut } from "./pagelinksout";
import { RecordApiOut } from "./recordapiout";
import { Expose, Type } from "class-transformer";

export class PageModelOutRecordApiOut extends SpeakeasyBase {
    /**
     * A array of returned items
     */
    @SpeakeasyMetadata({ elemType: RecordApiOut })
    @Expose({ name: "content" })
    @Type(() => RecordApiOut)
    content?: RecordApiOut[];

    /**
     * A collection of page URL links for navigation and iteration
     */
    @SpeakeasyMetadata()
    @Expose({ name: "links" })
    @Type(() => PageLinksOut)
    links?: PageLinksOut;

    /**
     * A collection page metadata
     */
    @SpeakeasyMetadata()
    @Expose({ name: "page" })
    @Type(() => PageInfoOut)
    page?: PageInfoOut;
}
