/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A collection page metadata
 */
export class PageInfoOut extends SpeakeasyBase {
    /**
     * The zero-indexed page number (must not be less than 0, defaults to 0)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "number" })
    number?: number;

    /**
     * The size of the page and maximum number of items to be returned (must not be less than 1, defaults to 20)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;

    /**
     * The total number of items available
     */
    @SpeakeasyMetadata()
    @Expose({ name: "totalElements" })
    totalElements?: number;

    /**
     * The total number of pages available based on the size
     */
    @SpeakeasyMetadata()
    @Expose({ name: "totalPages" })
    totalPages?: number;
}
