/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ApplicationPropertyApiOut } from "./applicationpropertyapiout";
import { FieldRecordApiOut } from "./fieldrecordapiout";
import { RecordDatesApiOut } from "./recorddatesapiout";
import { StepPropertyApiOut } from "./steppropertyapiout";
import { UserPropertyApiOut } from "./userpropertyapiout";
import { WorkflowPropertyApiOut } from "./workflowpropertyapiout";
import { Expose, Type } from "class-transformer";

/**
 * The status of the record
 */
export enum Status {
    Inactive = "INACTIVE",
    NotAssigned = "NOT_ASSIGNED",
    Assigned = "ASSIGNED",
    InProgress = "IN_PROGRESS",
    Complete = "COMPLETE",
}

/**
 * A array of returned items
 */
export class RecordApiOut extends SpeakeasyBase {
    /**
     * The parent application of the record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "application" })
    @Type(() => ApplicationPropertyApiOut)
    application?: ApplicationPropertyApiOut;

    /**
     * The creator of the record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "assignee" })
    @Type(() => UserPropertyApiOut)
    assignee?: UserPropertyApiOut;

    /**
     * The creator of the record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "creator" })
    @Type(() => UserPropertyApiOut)
    creator?: UserPropertyApiOut;

    /**
     * The origin step of the record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currentStep" })
    @Type(() => StepPropertyApiOut)
    currentStep?: StepPropertyApiOut;

    /**
     * Date information associated with the record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "dates" })
    @Type(() => RecordDatesApiOut)
    dates?: RecordDatesApiOut;

    /**
     * The fields and values of the record
     */
    @SpeakeasyMetadata({ elemType: FieldRecordApiOut })
    @Expose({ name: "fields" })
    @Type(() => FieldRecordApiOut)
    fields?: FieldRecordApiOut[];

    /**
     * The unique ID of this Risk Cloud resource
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The text value of the primary field of the record, otherwise the workflow prefix and sequence number of the record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Identifies the type of object this data represents
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object?: string;

    /**
     * The origin step of the record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "originStep" })
    @Type(() => StepPropertyApiOut)
    originStep?: StepPropertyApiOut;

    /**
     * The workflow prefix and sequence number of the record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "recordName" })
    recordName?: string;

    /**
     * The sequence number of the record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sequenceNumber" })
    sequenceNumber?: number;

    /**
     * The status of the record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: Status;

    /**
     * The parent workflow of the step
     */
    @SpeakeasyMetadata()
    @Expose({ name: "workflow" })
    @Type(() => WorkflowPropertyApiOut)
    workflow?: WorkflowPropertyApiOut;
}
