/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class SchemeBasic extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, name=password" })
    password: string;

    @SpeakeasyMetadata({ data: "security, name=username" })
    username: string;
}

export class Security extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=http;subtype=basic" })
    basic?: SchemeBasic;

    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    bearer?: string;
}
