/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WorkflowPropertyApiOut } from "./workflowpropertyapiout";
import { Expose, Type } from "class-transformer";

/**
 * Indicates which users are allowed to be assigned this step on a record
 */
export enum StepApiOutAssignableUserType {
    AppAndExternalUsers = "APP_AND_EXTERNAL_USERS",
    AppUsers = "APP_USERS",
    ExternalUsers = "EXTERNAL_USERS",
}

/**
 * The type of the step
 */
export enum StepApiOutType {
    Origin = "ORIGIN",
    Chain = "CHAIN",
    End = "END",
}

export class StepApiOut extends SpeakeasyBase {
    /**
     * Indicates which users are allowed to be assigned this step on a record
     */
    @SpeakeasyMetadata()
    @Expose({ name: "assignableUserType" })
    assignableUserType?: StepApiOutAssignableUserType;

    /**
     * Whether comments are displayed on a step
     */
    @SpeakeasyMetadata()
    @Expose({ name: "enableComments" })
    enableComments?: boolean;

    /**
     * Whether MFA is required for external users to access this step.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "externalUserMfaRequired" })
    externalUserMfaRequired?: boolean;

    /**
     * The unique ID of this Risk Cloud resource
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The name of the step
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Identifies the type of object this data represents
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object?: string;

    /**
     * The type of the step
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: StepApiOutType;

    /**
     * The parent workflow of the step
     */
    @SpeakeasyMetadata()
    @Expose({ name: "workflow" })
    @Type(() => WorkflowPropertyApiOut)
    workflow?: WorkflowPropertyApiOut;

    /**
     * The x-coordinate of the step in the application builder
     */
    @SpeakeasyMetadata()
    @Expose({ name: "xpos" })
    xpos?: number;

    /**
     * The y-coordinate of the step in the application builder
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ypos" })
    ypos?: number;
}
