/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The creator of the record
 */
export class UserPropertyApiOut extends SpeakeasyBase {
    /**
     * The email of the user
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * The unique ID of this Risk Cloud resource
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The name of the user
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Identifies the type of object this data represents
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object?: string;
}
