/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The type of the value
 */
export enum ValuePropertyApiOutType {
    Number = "NUMBER",
    Calculation = "CALCULATION",
    Attachment = "ATTACHMENT",
    Date = "DATE",
    Option = "OPTION",
    User = "USER",
    Text = "TEXT",
    Other = "OTHER",
}

/**
 * The values of the record field
 */
export class ValuePropertyApiOut extends SpeakeasyBase {
    /**
     * The unique ID of this Risk Cloud resource
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The numeric representation of the record value, with the format varying by value type:
     *
     * @remarks
     * - `NUMBER`: the numeric value of the number (example: `42.0`)
     * - `CALCULATION`: the numeric value of the calculation (example: `42.0`)
     * - `ATTACHMENT`: the version count of the attachment (example: `2.0`)
     * - `DATE`: the date measured in milliseconds since the Unix epoch (example: `1672552800000.0`)
     * - `OPTION`: the numeric value of the option (example: `2.0`)
     * - `USER`: a null value (example: `null`)
     * - `TEXT`: a null value (example: `null`)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "numericValue" })
    numericValue?: number;

    /**
     * Identifies the type of object this data represents
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object?: string;

    /**
     * The text representation of the record value, with the format varying by value type:
     *
     * @remarks
     * - `NUMBER`: a string representation of the number, with currency if specified on the field (example: `"42"`)
     * - `CALCULATION`: a string representation of the label if specified on the field, otherwise the number (example: `"Highest Risk"`)
     * - `ATTACHMENT`: the name of the attachment file (example: `"my-evidence.pdf"`)
     * - `DATE`: the date formatted according to the requesting user's settings (example: `"1/1/23, 12:00 PM"`)
     * - `OPTION`: the text value of the option (example: `"Medium Risk"`)
     * - `USER`: the full name and email of the user (example: `"First Last (first.last@example.com)"`)
     * - `TEXT`: the text value (example: `"Data Theft"`)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "textValue" })
    textValue?: string;

    /**
     * The type of the value
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: ValuePropertyApiOutType;
}
