/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The type of the relationship between workflows
 */
export enum WorkflowMapApiUpdateInRelationship {
    OneToOne = "OneToOne",
    OneToMany = "OneToMany",
    ManyToOne = "ManyToOne",
    ManyToMany = "ManyToMany",
}

/**
 * Workflow (Update)
 */
export class WorkflowMapApiUpdateIn extends SpeakeasyBase {
    /**
     * The type of the relationship between workflows
     */
    @SpeakeasyMetadata()
    @Expose({ name: "relationship" })
    relationship: WorkflowMapApiUpdateInRelationship;
}
