/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Workflow (Update)
 */
export class WorkflowApiUpdateIn extends SpeakeasyBase {
    /**
     * The name of the workflow
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The prefix to be used in the name of every record created from this workflow
     */
    @SpeakeasyMetadata()
    @Expose({ name: "recordPrefix" })
    recordPrefix?: string;

    /**
     * The x-coordinate of the workflow in the application builder (must not be less than 0)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "xpos" })
    xpos?: number;

    /**
     * The y-coordinate of the workflow in the application builder (must not be less than 0)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ypos" })
    ypos?: number;
}
