/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The type of the relationship between workflows
 */
export enum WorkflowMapApiOutRelationship {
    OneToOne = "OneToOne",
    OneToMany = "OneToMany",
    ManyToOne = "ManyToOne",
    ManyToMany = "ManyToMany",
}

export class WorkflowMapApiOut extends SpeakeasyBase {
    /**
     * The unique ID of the source workflow of the workflow map relationship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "from" })
    from?: string;

    /**
     * The unique ID of this Risk Cloud resource
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Identifies the type of object this data represents
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object?: string;

    /**
     * The type of the relationship between workflows
     */
    @SpeakeasyMetadata()
    @Expose({ name: "relationship" })
    relationship?: WorkflowMapApiOutRelationship;

    /**
     * The unique ID of the destination workflow of the workflow map relationship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "to" })
    to?: string;
}
