/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The parent workflow of the step
 */
export class WorkflowPropertyApiOut extends SpeakeasyBase {
    /**
     * The unique ID of this Risk Cloud resource
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The name of the workflow
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Identifies the type of object this data represents
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object?: string;

    /**
     * The prefix to be used in the name of every record created from this workflow
     */
    @SpeakeasyMetadata()
    @Expose({ name: "recordPrefix" })
    recordPrefix?: string;
}
