/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The type of the relationship between workflows
 */
export enum WorkflowMapApiCreateInRelationship {
    OneToOne = "OneToOne",
    OneToMany = "OneToMany",
    ManyToOne = "ManyToOne",
    ManyToMany = "ManyToMany",
}

/**
 * Workflow Map (Create)
 */
export class WorkflowMapApiCreateIn extends SpeakeasyBase {
    /**
     * The unique ID of the source workflow of the workflow map relationship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "from" })
    from: string;

    /**
     * The type of the relationship between workflows
     */
    @SpeakeasyMetadata()
    @Expose({ name: "relationship" })
    relationship: WorkflowMapApiCreateInRelationship;

    /**
     * The unique ID of the destination workflow of the workflow map relationship
     */
    @SpeakeasyMetadata()
    @Expose({ name: "to" })
    to: string;
}
